# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greeterwithtimestamp.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'greeterwithtimestamp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1agreeterwithtimestamp.proto\x12\x17greeterwithtimestamp.v1\x1a\x1fgoogle/protobuf/timestamp.proto\">\n\rWithTimestamp\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2r\n\x14GreeterWithTimestamp\x12Z\n\x08SayHello\x12&.greeterwithtimestamp.v1.WithTimestamp\x1a&.greeterwithtimestamp.v1.WithTimestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeterwithtimestamp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WITHTIMESTAMP']._serialized_start=88
  _globals['_WITHTIMESTAMP']._serialized_end=150
  _globals['_GREETERWITHTIMESTAMP']._serialized_start=152
  _globals['_GREETERWITHTIMESTAMP']._serialized_end=266
# @@protoc_insertion_point(module_scope)
