# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greeterwithduration.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'greeterwithduration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19greeterwithduration.proto\x12\x16greeterwithduration.v1\x1a\x1egoogle/protobuf/duration.proto\";\n\x0cWithDuration\x12+\n\x08\x64uration\x18\x01 \x01(\x0b\x32\x19.google.protobuf.Duration2m\n\x13GreeterWithDuration\x12V\n\x08SayHello\x12$.greeterwithduration.v1.WithDuration\x1a$.greeterwithduration.v1.WithDurationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeterwithduration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WITHDURATION']._serialized_start=85
  _globals['_WITHDURATION']._serialized_end=144
  _globals['_GREETERWITHDURATION']._serialized_start=146
  _globals['_GREETERWITHDURATION']._serialized_end=255
# @@protoc_insertion_point(module_scope)
